WebAppApiConsuming/Models/ErrorViewModel.cs
namespace WebAppApiConsuming.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebAppApiConsuming/Models/Region.cs
namespace WebAppApiConsuming.Models
{
    public class Region
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string AreaName { get; set; }

        public double Area { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public long Population { get; set; }
    }
}

WebAppApiConsuming/Models/User.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebAppApiConsuming.Models
{
    public class User
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}

WebAppApiConsuming/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebAppApiConsuming.Models;

namespace WebAppApiConsuming.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebAppApiConsuming/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using WebAppApiConsuming.Models;

namespace WebAppApiConsuming.Controllers
{
    public class LoginController : Controller
    {
        public  IActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Index(User user)
        {
            using (var httpClient = new HttpClient())
            {
                StringContent stringContent = new StringContent(JsonConvert.SerializeObject(user), Encoding.UTF8, "application/json");
                using (var response = await httpClient.PostAsync("http://localhost:5214/api/Auth/Login", stringContent))
                {
                    //To get all roles for the user
                    using (var res = await httpClient.PostAsync("http://localhost:5214/api/Auth/", stringContent))
                    {
                        string strRoles = await res.Content.ReadAsStringAsync();
                        var roles = JsonConvert.DeserializeObject<List<string>>(strRoles);
                        TempData["Roles"] = roles;
                    }

                    string token = await response.Content.ReadAsStringAsync();
                    if (token == "Invalid  Username or password")
                    {
                        ViewBag.Message = "Invalid  Username or password";
                        return Redirect(nameof(Index));
                    }
                    HttpContext.Session.SetString("Jwt", token);
                }

                return Redirect("Region/Index");//if token is validated we should be redirected to Region Controller's index action method to show all region data
            }
        }
        public async Task<IActionResult> Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction(nameof(Index));
        }


    }
}

WebAppApiConsuming/Controllers/RegionController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebAppApiConsuming.Models;
using System.Net.Http.Headers;
using System.Text;

namespace WebAppApiConsuming.Controllers
{
    public class RegionController : Controller
    {
        public static string baseUrl = "http://localhost:5214/api/Regions/";

        
        public async Task<IActionResult> Index()
        {
            var regions = await GetAllRegions();

            ViewBag.Roles = TempData["Roles"];
            TempData.Keep("Roles");
            foreach (var role in ViewBag.Roles)
            {
                if (role == "admin")
                {
                    ViewBag.Role = "admin";
                }
            }

            return View(regions);
        }
        public async Task<List<Region>> GetAllRegions()
        {
            var accessToken = HttpContext.Session.GetString("Jwt");
            var url = baseUrl;
            HttpClient client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer",accessToken);
            string jsonString = await client.GetStringAsync(url);
            var res = JsonConvert.DeserializeObject<List<Region>>(jsonString);
            return res.ToList();
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Code,AreaName,Area,Latitude,Longitude,Population")] Region region)
        {
            var accessToken = HttpContext.Session.GetString("Jwt");
            HttpClient client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            var stringContent = new StringContent(JsonConvert.SerializeObject(region), Encoding.UTF8, "application/json");
            await client.PostAsync(baseUrl, stringContent);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var accessToken = HttpContext.Session.GetString("Jwt");
            var url = baseUrl + id;
            HttpClient client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            string jsonStr = await client.GetStringAsync(url);
            var res = JsonConvert.DeserializeObject<Region>(jsonStr);
            if (res == null)
            {
                return NotFound();
            }
            return View(res);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Code,AreaName,Area,Latitude,Longitude,Population")] Region regions)
        {
            if (id != regions.Id)
            {
                return NotFound();
            }
            var accessToken = HttpContext.Session.GetString("Jwt");
            var url = baseUrl + id;
            HttpClient client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            var stringContent = new StringContent(JsonConvert.SerializeObject(regions), Encoding.UTF8, "application/json");
            await client.PutAsync(url, stringContent);
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var accessToken = HttpContext.Session.GetString("Jwt");
            var url = baseUrl + id;
            HttpClient client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            string jsonStr = await client.GetStringAsync(url);
            var res = JsonConvert.DeserializeObject<Region>(jsonStr);
            if (res == null)
            {
                return NotFound();
            }
            return View(res);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var accessToken = HttpContext.Session.GetString("Jwt");
            var url = baseUrl + id;
            HttpClient client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            await client.DeleteAsync(url);
            return RedirectToAction(nameof(Index));
        }
    }
}

WebAppApiConsuming/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>
<div class="col-6 text-end">
    <a asp-controller="Login" asp-action="Index" class="btn btn-outline-primary"><i class="bi bi-plus-circle-dotted"></i> Login</a>
</div>

WebAppApiConsuming/Views/Login/Index.cshtml
@model WebAppApiConsuming.Models.User
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

<h1>Login Form</h1>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Index" asp-controller="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div clss="form-group">
                <label asp-for="@Model.UserName" class="Control-label">UserName</label>
                <input asp-for="UserName" class="form-control"/>
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>

            <div clss="form-group">
                <label asp-for="@Model.Password" class="Control-label">Password</label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-primary" />
            </div>
            <label>@Html.Raw(@ViewBag.Message)</label>
        </form>
    </div>
</div>

WebAppApiConsuming/Views/Region/Create.cshtml
@model WebAppApiConsuming.Models.Region
@{
    ViewData["Title"] = "Add Region";
}

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Add Region</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Code"></label>
            <input asp-for="Code" class="form-control" />
            <span asp-validation-for="Code" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="AreaName"></label>
            <input asp-for="AreaName" class="form-control" />
            <span asp-validation-for="AreaName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Area"></label>
            <input asp-for="Area" class="form-control" />
            <span asp-validation-for="Area" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Latitude"></label>
            <input asp-for="Latitude" class="form-control" />
            <span asp-validation-for="Latitude" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Longitude"></label>
            <input asp-for="Longitude" class="form-control" />
            <span asp-validation-for="Longitude" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Population"></label>
            <input asp-for="Population" class="form-control" />
            <span asp-validation-for="Population" class="text-danger"></span>
        </div>
        <button class="btn btn-primary" style="width:150px">Submit</button>
        <a asp-controller="Region" asp-action="Index" class="btn btn-secondary" style="width:150px">Back</a>
    </div>
</form>
@section Scripts
    {
    <partial name="_ValidationScriptsPartial.cshtml" />
}

WebAppApiConsuming/Views/Region/Delete.cshtml
@model WebAppApiConsuming.Models.Region
@{
    ViewData["Title"] = "Delete Region";
}

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Region</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Code"></label>
            <input asp-for="Code" disabled class="form-control" />
            <span asp-validation-for="Code" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="AreaName"></label>
            <input asp-for="AreaName" disabled class="form-control" />
            <span asp-validation-for="AreaName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Area"></label>
            <input asp-for="Area" disabled class="form-control" />
            <span asp-validation-for="Area" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Latitude"></label>
            <input asp-for="Latitude" disabled class="form-control" />
            <span asp-validation-for="Latitude" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Longitude"></label>
            <input asp-for="Longitude" disabled class="form-control" />
            <span asp-validation-for="Longitude" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Population"></label>
            <input asp-for="Population" disabled class="form-control" />
            <span asp-validation-for="Population" class="text-danger"></span>
        </div>
        <button class="btn btn-primary" style="width:150px">Delete</button>
        <a asp-controller="Region" asp-action="Index" class="btn btn-secondary" style="width:150px">Back</a>
    </div>
</form>
@section Scripts
    {
    <partial name="_ValidationScriptsPartial.cshtml" />
}

WebAppApiConsuming/Views/Region/Edit.cshtml
@model WebAppApiConsuming.Models.Region
@{
    ViewData["Title"] = "Edit Region";
}

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Region</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Code"></label>
            <input asp-for="Code" class="form-control" />
            <span asp-validation-for="Code" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="AreaName"></label>
            <input asp-for="AreaName" class="form-control" />
            <span asp-validation-for="AreaName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Area"></label>
            <input asp-for="Area" class="form-control" />
            <span asp-validation-for="Area" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Latitude"></label>
            <input asp-for="Latitude" class="form-control" />
            <span asp-validation-for="Latitude" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Longitude"></label>
            <input asp-for="Longitude" class="form-control" />
            <span asp-validation-for="Longitude" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Population"></label>
            <input asp-for="Population" class="form-control" />
            <span asp-validation-for="Population" class="text-danger"></span>
        </div>
        <button class="btn btn-primary" style="width:150px">Submit</button>
        <a asp-controller="Region" asp-action="Index" class="btn btn-secondary" style="width:150px">Back</a>
    </div>
</form>
@section Scripts
    {
    <partial name="_ValidationScriptsPartial.cshtml" />
}

WebAppApiConsuming/Views/Region/Index.cshtml
@model IEnumerable<WebAppApiConsuming.Models.Region>
@{
    ViewData["Title"] = "All Regions";
}




<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">All Regions</h2>
        </div>
        <div class="col-6 text-end">
            @if (ViewBag.Role == "admin")
            {
                <a asp-controller="Region" asp-action="Create" class="btn btn-outline-primary"><i class="bi bi-plus-circle-dotted"></i> Add</a>
            }
        </div>
    </div>
</div>

<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Code
            </th>
            <th>
                Area Name
            </th>
            <th>
                Area
            </th>
            <th>
                Latitude
            </th>
            <th>
                Longitude
            </th>
            <th>
                Population
            </th>
            @if (ViewBag.Role == "admin")
            {
                <th>
                Edit | Delete
                </th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var c in Model)
        {
            <tr>
                <td>@c.Code</td>
                <td>@c.AreaName</td>
                <td>@c.Area</td>
                <td>@c.Latitude</td>
                <td>@c.Longitude</td>
                <td>@c.Population</td>

                @if (ViewBag.Role == "admin")
                {
                    <td>
                        <div class="btn-group m-75" role="group">
                            <a asp-controller="Region" asp-action="Edit" asp-route-id="@c.Id" class="btn btn-outline-primary"><i class="bi bi-pencil"></i>Edit</a>
                            <a asp-controller="Region" asp-action="Delete" asp-route-id="@c.Id" class="btn btn-outline-primary"><i class="bi bi-trash3"></i>Delete</a>
                        </div>
                    </td>
                }      
            </tr>
        }
    </tbody>
</table>

WebAppApiConsuming/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAppApiConsuming</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebAppApiConsuming.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAppApiConsuming</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebAppApiConsuming - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebAppApiConsuming/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAppApiConsuming</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebAppApiConsuming.styles.css" asp-append-version="true" />
</head>
<body>
   @* <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAppApiConsuming</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>*@
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebAppApiConsuming - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>